[book]
authors = ["The OurMachinery Team"]
language = "en"
multilingual = false
src = "src"
title = "The Machinery Book"

[output.html]
git-repository-url = "https://github.com/OurMachinery/themachinery-books"

[output.html.fold]
enable = true

[preprocessor.toc]
command = "tmbook toc"
renderer = ["html"]
marker = "* {:toc}"

[preprocessor.links]


[preprocessor.path_replacement]
renderer = ["html"]
books = ["the_machinery_book"]
command = "./tmbook path_replacement"


[preprocessor.auto_doc]
renderer = ["html"]
books = ["the_machinery_book"]
command = "./tmbook auto_doc"

[preprocessor.auto_include]
renderer = ["html"]
books = ["the_machinery_book"]
command = "./tmbook auto_include"

