[book]
authors = ["The OurMachinery Team"]
language = "en"
multilingual = false
src = "src"
title = "The Machinery Tutorial Book"

[output.html]
git-repository-url = "https://github.com/OurMachinery/themachinery-books"

[output.html.fold]
enable = true

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
marker = "* auto-gen TOC;\n{:toc}"

[preprocessor.path_replacement]
renderer = ["html"]
folder = "../"
books = ["the_machinery_book","tutorials"]
command = "python ../path_replacement.py"

[preprocessor.links]

[output.linkcheck]
follow-web-links = false
exclude = [ 'https://ourmachinery\.com/apidoc/','mailto:ping@ourmachinery\.com','https://marketplace\.visualstudio\.com'  ]




#[preprocessor.autolink]
#renderer = ["html"]
#folder = "../"
#books = ["the_machinery_book","tutorials"]
#command = "python ../autogenerete_doc_links.py"

[preprocessor.auto_include]
renderer = ["html"]
folder = "../"
books = ["the_machinery_book","tutorials"]
command = "python ../auto_include.py"

[preprocessor.authors]
renderer = ["html"]
folder = "../"
books = ["the_machinery_book","tutorials"]
command = "python ../authors.py"