[book]
authors = ["The OurMachinery Team"]
language = "en"
multilingual = false
src = "src"
title = "The Machinery Tutorial Book"

[output.html]
git-repository-url = "https://github.com/OurMachinery/themachinery-books"

[output.html.fold]
enable = true

[preprocessor.toc]
command = "../tmbook toc"
renderer = ["html"]
marker = "* auto-gen TOC;\n{:toc}"

[preprocessor.links]


[preprocessor.path_replacement]
renderer = ["html"]
folder = "../"
books = ["the_machinery_book","tutorials"]
command = "../tmbook path_replacement"


[preprocessor.auto_doc]
renderer = ["html"]
folder = "../"
books = ["the_machinery_book","tutorials"]
command = "../tmbook auto_doc"

[preprocessor.auto_include]
renderer = ["html"]
folder = "../"
books = ["the_machinery_book","tutorials"]
command = "../tmbook auto_include"

[preprocessor.authors]
renderer = ["html"]
folder = "../"
books = ["the_machinery_book","tutorials"]
command = "../tmbook authors"

#[output.linkcheck]
#command = "mdbook-bin/mdbook-linkcheck"
#folder = "../"
#follow-web-links = false
#exclude = [ 'https://ourmachinery\.com/apidoc/','mailto:ping@ourmachinery\.com','https://marketplace\.visualstudio\.com'  ]