name: build github page
on:
  workflow_dispatch:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TM_BOOK_CODE_SNIPPETS: ${{github.workspace}}/samples/examples
      TM_SDK_DIR:  ${{github.workspace}}/sdk_dir/headers
    steps:
      - name: Checkout website
        uses: actions/checkout@v2
        with:
          path: ./
      - name: Checkout themachinery-book-code-snippets repo
        uses: actions/checkout@v2
        with:
          path: samples
          repository: OurMachinery/themachinery-book-code-snippets
          token: ${{ secrets.SAMPLE_REPO_TOKEN }}
      - name: download SDK
        run: |
          sudo apt install -y unzip wget
          wget https://ourmachinery.com/releases/2022.1/the-machinery-2022.1.a-linux.zip
          mkdir sdk_dir
          unzip the-machinery-2022.1.a-linux.zip -d sdk_dir
      - name: Setup tmbook
        run: |
          wget https://github.com/simon-ourmachinery/tmbook/releases/download/latest/tmbook
          chmod +x tmbook
      - name: download css and js dependencies
        run: |
          cd public
          mkdir css
          cd css
          wget https://ourmachinery.com/css/bootstrap.min.css
          wget https://ourmachinery.com/css/style.min.css
          cd ..
          mkdir js
          cd js
          wget https://ourmachinery.com/js/bootstrap.bundle.min.js
          wget https://ourmachinery.com/js/page.min.js
      - name: Build the_machinery_book
        run: |
          export PATH="${{github.workspace}}/mdbook_tera/bin:$PATH"
          export PATH="${{github.workspace}}/tools/:$PATH"
          cd the_machinery_book
          sed -i "s/#//" book.toml
          ../tmbook build
          mv book/html ../public/the_machinery_book
      - name: Build tutorials
        run: |
          export PATH="${{github.workspace}}/mdbook_tera/bin:$PATH"
          export PATH="${{github.workspace}}/tools/:$PATH"
          cd tutorials
          sed -i "s/#//" book.toml
          ../tmbook build
          mv book/html ../public/tutorials
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
      - name: Report
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        if: always()
