name: build github page
on:
  workflow_dispatch:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TM_BOOK_CODE_SNIPPETS: ${{github.workspace}}/samples/examples
      TM_SDK_DIR:  ${{github.workspace}}/sdk_dir
    steps:
      - name: Checkout website
        uses: actions/checkout@v2
        with:
          path: ./
      - name: Checkout themachinery-book-code-snippets repo
        uses: actions/checkout@v2
        with:
          path: samples
          repository: OurMachinery/themachinery-book-code-snippets
          token: ${{ secrets.SAMPLE_REPO_TOKEN }}
      - name: download SDK
        run: |
          sudo apt install -y unzip wget
          wget https://ourmachinery.com/releases/2021.9/the-machinery-2021.9-linux.zip
          mkdir sdk_dir
          unzip the-machinery-2021.9-linux.zip -d sdk_dir
      - name: Cache mdbook-tera
        id: cache-mdbook-tera
        uses: actions/cache@v2
        with:
          path: ./mdbook_tera
          key: ${{ runner.os }}-mdbook-tera
      - uses: actions-rs/cargo@v1
        if: steps.cache-mdbook-tera.outputs.cache-hit != 'true'
        with:
          command: install
          args: mdbook-tera --root ./mdbook_tera
      - name: add mdbook-tera to PATH
        run: |
          export PATH="${{github.workspace}}/mdbook_tera/bin:$PATH"
          chmod +x ./mdbook_tera/bin/mdbook-tera
      - run: sudo apt update && sudo apt install zip
      - name: Setup mdbook
        run: |
          mkdir tools
          cd tools
          wget https://github.com/rust-lang/mdBook/releases/download/v0.4.10/mdbook-v0.4.10-x86_64-unknown-linux-gnu.tar.gz -O archive.tar.gz
          tar -xf archive.tar.gz
          chmod +x mdbook
          wget https://github.com/badboy/mdbook-toc/releases/download/0.7.0/mdbook-toc-0.7.0-x86_64-unknown-linux-gnu.tar.gz -O mdbook-toc.tar.gz
          tar -xf  mdbook-toc.tar.gz
          chmod +x mdbook-toc
          wget https://github.com/Michael-F-Bryan/mdbook-linkcheck/releases/download/v0.7.4/mdbook-linkcheck.v0.7.4.x86_64-unknown-linux-gnu.zip -O mdbook-linkcheck.zip
          unzip  mdbook-linkcheck.zip
          chmod +x mdbook-linkcheck
          cd ../
          mkdir public
          cp index.html public/index.html
      - name: download css and js dependencies
        run: |
          cd public
          mkdir css
          cd css
          wget https://ourmachinery.com/css/bootstrap.min.css
          wget https://ourmachinery.com/css/style.min.css
          cd ..
          mkdir js
          cd js
          wget https://ourmachinery.com/js/bootstrap.bundle.min.js
          wget https://ourmachinery.com/js/page.min.js
      - name: Build introduction
        run: |
          export PATH="${{github.workspace}}/mdbook_tera/bin:$PATH"
          export PATH="${{github.workspace}}/tools/:$PATH"
          cd the_machinery_book
          sed -i "s/#//" book.toml
          mdbook build
          mv book/html ../public/the_machinery_book
      - name: Build introduction
        run: |
          export PATH="${{github.workspace}}/mdbook_tera/bin:$PATH"
          export PATH="${{github.workspace}}/tools/:$PATH"
          cd tutorials
          sed -i "s/#//" book.toml
          mdbook build
          mv book/html ../public/tutorials
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
