name: build github page
on:
  workflow_dispatch:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TM_BOOK_CODE_SNIPPETS: ${{github.workspace}}/samples/examples
      TM_SDK_DIR:  ${{github.workspace}}/sdk_dir/headers
    steps:
      - name: Checkout website
        uses: actions/checkout@v2
        with:
          path: ./
      - name: Checkout themachinery-book-code-snippets repo
        uses: actions/checkout@v2
        with:
          path: samples
          repository: OurMachinery/themachinery-book-code-snippets
          token: ${{ secrets.SAMPLE_REPO_TOKEN }}
      - name: download SDK
        run: |
          sudo apt install -y unzip wget
          wget https://ourmachinery.com/releases/2022.2/the-machinery-2022.2-linux.zip
          mkdir sdk_dir
          unzip the-machinery-2022.2-linux.zip -d sdk_dir
      - name: Setup tmbook
        run: |
          wget https://github.com/simon-ourmachinery/tmbook/releases/download/latest/tmbook
          chmod +x tmbook
      - name: Build book
        run: |
          sed -i "s/#//" book.toml
          ./tmbook build
          cp CNAME book/CNAME
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
      - name: Report
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        if: always()
